#!/usr/bin/env python
import sys

if __name__ == "__main__":
    try:
        if sys.argv[1] == "pdu":
            from pdusim import cli
        else:
            from infrasim import cli
        cli.command_handler()
    except ImportError as e:
        print e
